apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    enableRepoMirroring: true
    imagePullSecretName: redhat-pull-secret
    superuserCredentialsSecretName: quay-super-user
    configSecretName: quay-config-app
    securityContext:
      fsGroup: 1001
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
    updateInterval: "60m"
  redis:
    credentialsSecretName: quay-redis-password
    imagePullSecretName: redhat-pull-secret
