apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    enableRepoMirroring: true
    keepConfigDeployment: true
    superuserCredentialsSecretName: quay-super-user
    database:
      volumeSize: 10Gi
    imagePullSecretName: redhat-pull-secret
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi
    securityContext:
      fsGroup: 1001
    resources:
      requests:
        memory: 6Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "2"
    configResources:
      requests:
        memory: 512Mi
        cpu: 400m
      limits:
        memory: 512Mi
        cpu: 400m
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
