apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    enableRepoMirroring: true
    keepConfigDeployment: true
    database:
      volumeSize: 10Gi
    imagePullSecretName: redhat-pull-secret
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
    persistentVolumeSize: 10Gi
    securityContext:
      fsGroup: 1001
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
